# Generated by Django 4.1.2 on 2022-11-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appconsultorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nacimiento',
        ),
    ]
